---

# Generate password with: 
# python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'

- name: User Create
  hosts: all

  tasks:
    - name: Creating user 
      user: 
        name={{user}}
        password={{password}}
      when: act == "add" and groupz is undefined

  tasks:
    - name: Creating user with adding to specified Groups 
      user: 
        name={{user}}
        password={{password}}
        groups={{groupz}}
      when: act == "add" and groupz is defined 

  tasks:
    - name: Removing user 
      user: 
        name={{user}}
        state=absent
      when: action == "rem"
