---

# Generate password with: 
# python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'

- name: User Create
  hosts: all

  tasks:
    - name: Creating user 
      user: 
        name={{user}}
        password={{password}}
      when: groups is not defined

  tasks:
    - name: Creating user with adding to specified Groups 
      user: 
        name={{user}}
        password={{password}}
        groups={{groups}}
      when: groups in defined 
