---
- name: Hello World!
  hosts: all
 
  tasks:
 
  - name: "Cahnge Config"
    lineinfile:
       backup: yes
       path: /etc/zabbix/zabbix_agent2.conf
       state: present
       regexp: '^Server='
       line: 'Server=10.9.0.80,10.9.0.81,10.9.0.82,172.18.0.0/16'

  - name: Reload service httpd, in all cases
    ansible.builtin.systemd:
       name: zabbix-agent2
       state: restarted
