---
- name: Zabbix Agent Config Changing
  hosts: all
 
  tasks:
 
  - name: "Change Config"
    lineinfile:
       backup: yes
       path: /etc/zabbix/zabbix_agent2.conf
       state: present
       regexp: '^Server='
       line: 'Server=10.9.0.80,10.9.0.81,10.9.0.82,172.18.0.0/16'
    register: zbxconfig

  - name: Reload Systemd service zabbix-agent2
    ansible.builtin.systemd:
       name: zabbix-agent2
       state: restarted
    when: zbxconfig.changed and ansible_distribution_version >= '7'

  - name: Reload SysV service zabbix-agent2
    sysvinit:
       name: zabbix-agent2
       state: restarted
    when: zbxconfig.changed and ansible_distribution_version <= '7'
