---
- name: SSH hardening
  hosts: all
 
  tasks:

  - name: "Replace or Add Ciphers"
    lineinfile:
       backup: yes
       path: /etc/ssh/sshd_config
       state: present
       regexp: '^Ciphers'
       line: 'Ciphers aes128-ctr,aes192-ctr,aes256-ctr'
       validate: '/usr/sbin/sshd -t -f %s'
    register: ciphers_mod

  - name: "Replace or Add KexAlgorithms"
    lineinfile:
       backup: yes
       path: /etc/ssh/sshd_config
       state: present
       regexp: '^KexAlgorithms'
       line: 'KexAlgorithms ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256 ERROR_TEST'
       validate: '/usr/sbin/sshd -t -f %s'
    register: kex_mod

  - name: "Replace or Add MACs"
    lineinfile:
       backup: yes
       path: /etc/ssh/sshd_config
       state: present
       regexp: '^MACs'
       line: 'MACs hmac-sha2-256,hmac-sha2-512'
       validate: '/usr/sbin/sshd -t -f %s'
    register: macs_mod

  - name: Reload Systemd ssh service
    ansible.builtin.systemd:
       name: sshd
       state: restarted
    when: (ciphers_mod.changed == true or kex_mod.changed == true or macs_mod.changed == true) and ansible_distribution_version >= '7'

  - name: Reload SysV ssh service
    sysvinit:
       name: sshd
       state: restarted
    when: (ciphers_mod.changed == true or kex_mod.changed == true or macs_mod.changed == true) and ansible_distribution_version <= '7'    
 
