---
- name: Deny SSH Root Login
  hosts: all
 
  tasks:

  - name: Check sshd config file
    stat:
      path: /etc/ssh/sshd_config
    register: checkfile

  - name: "Deny SSH Root Login"
    lineinfile:
       backup: yes
       path: /etc/ssh/sshd_config
       state: present
       regexp: 'PermitRootLogin yes'
       line: 'PermitRootLogin no'
    when: checkfile.stat.exists == true and answer == "n"
    register: n
 
  - name: "Permit SSH Root Login"
    lineinfile:
       backup: yes
       path: /etc/ssh/sshd_config
       state: present
       regexp: 'PermitRootLogin no'
       line: 'PermitRootLogin yes'
    when: checkfile.stat.exists == true and answer == "y"
    register: y

  - name: Reload Systemd ssh service
    ansible.builtin.systemd:
       name: sshd
       state: restarted
    when: y.changed == true or n.changed == true and ansible_distribution_version >= '7'

  - name: Reload SysV ssh service
    sysvinit:
       name: sshd
       state: restarted
    when: y.changed == true or n.changed == true and ansible_distribution_version <= '7'                                                                      

