---
- name: Zabbix Agent Config Changing
  hosts: all
 
  tasks:
 
  - name: install the latest version of Apache from the testing repo
    yum:
       name: perl
       state: present

  - name: Check if VMWare Tools Service Exists
    stat:
      path=/etc/init.d/vmware-tools
    register: vmw_service

  - name: Check if OpenVM Tools Service Exists
    stat:
      path=/usr/lib/systemd/system/vmtoolsd.service
    register: ovm_service

  - name: Remove OpenVM Tools
    become: yes
    yum: 
      name: open-vm-tools
      state: absent
    when: ovm_service.stat.exists == true
     
  - name: Copy VMWare Tools Installation Files
    synchronize:
      src: ./vmware-tools-distrib/
      dest: /tmp/vmware-tools-distrib
    when: vmw_service.stat.exists == false
     
  - name: Install VMWare Tools
    become: yes
    command: perl /tmp/vmware-tools-distrib/vmware-install.pl -d default -f
    when: vmw_service.stat.exists == false
