- name: Install Zabbix repository from a remote repo
  yum:
    name: https://repo.zabbix.com/zabbix/5.4/rhel/7/x86_64/zabbix-release-5.4-1.el7.noarch.rpm
    state: present

- name: Install zabbix-agent2
  yum:
    name: zabbix-agent2
    state: present
    
- name: Enable zabbix-agent2 service
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: started
    enabled: yes    
